data: # root path of train/validation data (either relative/absoulte path is ok)
  train: 'training_data'
  validation: 'training_data'
---
train:
  rep_discriminator: 1
  num_workers: 48
  batch_size: 64
  optimizer: 'adam'
  epochs: 1000
  adam:
    init_lr: 0.0001
    final_lr: 0.00001
    beta1: 0.5
    beta2: 0.9
---
audio:
  mel_bias: 7.0
  n_mel_channels: 80
  segment_length: 15360 # 256 * 60
  pad_short: 1024 # 256 * 4
  filter_length: 1024
  hop_length: 256 # WARNING: this can't be changed.
  win_length: 1024
  sampling_rate: 22050
  mel_fmin: 50.0
  mel_fmax: 7600.0
---
model:
  feat_match: 10.0
---
log:
  summary_interval: 1
  validation_interval: 5
  save_interval: 25
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
